steps:
- name: "gcr.io/cloud-builders/docker"
  id: "Build"
  args:
    [
      "build",
      ".",
      "-f",
      "dockerfiles/train.dockerfile",
      "-t",
      "europe-west1-docker.pkg.dev/mlops-72/mlops-72-registry/train-image:latest"
    ]

- name: "gcr.io/cloud-builders/docker"
  id: "Push"
  args:
    [
      "push",
      "europe-west1-docker.pkg.dev/mlops-72/mlops-72-registry/train-image:latest"
    ]

options:
  logging: CLOUD_LOGGING_ONLY
